export const nav = [
  { href: '/about', label: 'Profile' }, { href: '/experience', label: 'Experience' },
  { href: '/projects', label: 'Selected work' }, { href: '/ai-emerging-technology', label: 'AI practice' },
  { href: '/capabilities', label: 'Capabilities' },
];

export const projects = [
  { slug:'connectivity-on-demand', title:'Connectivity on Demand', organisation:'CSquared', period:'2022—2024', number:'01', discipline:'Platform leadership · Connectivity', image:'/assets/projects/project-connectivity-on-demand-concept-v1.png', summary:'Leading product and engineering work for an API-driven connectivity platform designed to make complex network services easier to provision and operate across markets.', role:'Product and engineering leadership across roadmap, architecture and multidisciplinary delivery.', challenge:'Turn a distributed, technically complex connectivity environment into a coherent platform experience for customers and operations teams.', approach:['Translate market and customer needs into a product roadmap.','Connect service orchestration, APIs and operating workflows.','Align product, engineering and stakeholder decisions around clear platform boundaries.','Build for repeatable delivery across distinct market contexts.'], significance:'A strong example of executive product judgment staying connected to architecture and delivery. Public metrics are intentionally withheld until confirmed.' },
  { slug:'hardware-independent-sd-wan', title:'Hardware-independent SD-WAN', organisation:'CSquared', period:'2022—2024', number:'02', discipline:'Network orchestration', image:'/assets/projects/project-sd-wan-concept-v1.png', summary:'A centrally controlled connectivity approach designed around interoperability and reduced dependence on proprietary appliances.', role:'Led product and technical direction across a multidisciplinary delivery environment.', challenge:'Create more flexible service orchestration without locking the operating model to a single hardware vendor.', approach:['Frame interoperability as a product requirement.','Use central control to simplify policy and operations.','Sequence technical delivery around customer and operational value.','Coordinate architecture, product and implementation trade-offs.'], significance:'Demonstrates product leadership at the intersection of software, networks and enterprise operations. Its programme relationship to Connectivity on Demand remains under factual review.' },
  { slug:'iot-sim-lifecycle', title:'IoT SIM Lifecycle', organisation:'Safaricom', period:'2019—2021', number:'03', discipline:'Enterprise IoT', image:'/assets/projects/project-iot-sim-lifecycle-concept-v1.png', summary:'Enterprise workflows spanning activation, suspension, billing and bulk SIM operations.', role:'Designed and implemented platform workflows and integrations.', challenge:'Make high-volume connected-device administration more manageable for enterprise users and internal teams.', approach:['Map the full operational lifecycle.','Design backend services and integration points.','Support bulk actions without losing control or traceability.','Connect product workflows to billing and enterprise operations.'], significance:'Shows hands-on platform engineering applied to a commercially important IoT operating problem. Quantified outcomes await confirmation.' },
  { slug:'base-station-management', title:'Base Station Management', organisation:'Safaricom', period:'2019—2021', number:'04', discipline:'Connected infrastructure', image:'/assets/projects/project-base-station-management-concept-v1.png', summary:'A unified management layer connecting operational components across distributed sites.', role:'Developed the platform and its component integrations.', challenge:'Bring fragmented site components into a more coherent management and operational view.', approach:['Model distributed infrastructure as an integrated system.','Create services around the key operational workflows.','Connect component data and control paths.','Design for maintainability in a real operating environment.'], significance:'A practical systems story connecting software engineering, IoT and infrastructure operations. Reported savings remain unpublished pending verification.' },
] as const;

export const roles = [
  ['2025—Now','Director / CTO','Cognativ','Technology strategy, engineering leadership and platform delivery.'],
  ['2024—2025','Product Development Specialist','Go City','Requirements, integrations, testing, releases and workflow improvement.'],
  ['2022—2024','Products Development Lead','CSquared','Product and engineering leadership for connectivity platforms across African markets.'],
  ['2021—2022','Manager, Enterprise Solutions','Safaricom','Solution architecture across cloud, connectivity, IoT, security and integration.'],
  ['2019—2021','IoT Engineer','Safaricom','Enterprise IoT platforms, APIs and operational integrations.'],
  ['2015—2019','Engineer · Team Lead · Facilitator','AARL / Andela','Python delivery, team leadership, code review and developer mentorship.'],
] as const;
